version: '3.9'
services:
  api:
    build:
      dockerfile: ./docker/dev.Dockerfile
      context: '..'
    volumes:
      - ../src:/usr/src/app/src
      - ../package.json:/usr/src/app/package.json
      - ../yarn.lock:/usr/src/app/yarn.lock

  db:
    volumes:
      - ../sql_scripts/aniskip-database-backup/db.dump:/docker-entrypoint-initdb.d/db.dump
      - ../sql_scripts/load_input.sh:/docker-entrypoint-initdb.d/load_input.sh
