version: '3.9'
services:
  api:
    build:
      dockerfile: ./docker/Dockerfile
      context: '..'
    ports:
      - '5000:5000'
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend
    volumes:
      - database_data:/var/lib/postgresql/data
      - ../sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../sql_scripts/test_input.sql:/docker-entrypoint-initdb.d/test_input.sql

networks:
  backend:
    driver: bridge

volumes:
  database_data:
