version: '3.9'
services:
  api:
    image: lexesjan/aniskip-api
    restart: always
    ports:
      - '5000:5000'
    networks:
      - network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: lexesjan/aniskip-database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - network
    volumes:
      - database_data:/var/lib/postgresql/data

networks:
  network:
    driver: bridge

volumes:
  database_data:
